--[[ 
    Generated by Obfuscator Tool
    Status: Protected
]]--

local _0x5a2f = {"\82\101\112\108\105\99\97\116\101\100\83\116\111\114\97\103\101", "\87\111\114\107\115\112\97\99\101", "\80\108\97\121\101\114\115", "\76\105\103\104\116\105\110\103", "\83\110\111\119\109\97\110", "\69\103\103\115", "\67\97\109\101\114\97"}
local _v1 = game:GetService(_0x5a2f[1])
local _v2 = game:GetService(_0x5a2f[2])
local _v3 = game:GetService(_0x5a2f[3])
local _v4 = game:GetService(_0x5a2f[4])
local _v5 = _v3.LocalPlayer

local _settings = {e = _0x5a2f[5], a = 8, s = 0}

local function _clean()
    for _, v in pairs(_v2:GetChildren()) do
        if v.Name ~= _v5.Name and v.Name ~= _0x5a2f[7] and v.Name ~= _0x5a2f[6] and not v:IsA("\84\101\114\114\97\105\110") then
            pcall(function() v:Destroy() end)
        end
    end
    local ef = _v2:FindFirstChild(_0x5a2f[6])
    if ef then
        for _, e in pairs(ef:GetChildren()) do
            if not e.Name:find(_settings.e) then
                pcall(function() e:Destroy() end)
            end
        end
    end
    _v2.Terrain:Clear()
end

local function _fx()
    _v4.GlobalShadows = false
    _v4.FogEnd = 9e9
    for _, v in pairs(_v4:GetChildren()) do
        if v:IsA("\80\111\115\116\69\102\102\101\99\116") or v:IsA("\83\107\121") or v:IsA("\67\108\111\117\100\115") then
            v:Destroy()
        end
    end
end

local function _hide(m)
    if m then
        for _, v in pairs(m:GetDescendants()) do
            if v:IsA("\66\97\115\101\80\97\114\116") then
                v.Transparency = 1
                v.CastShadow = false
            elseif v:IsA("\68\101\99\97\108") or v:IsA("\84\101\120\116\117\114\101") then
                v:Destroy()
            end
        end
    end
end

local function _getRemote()
    for _, v in ipairs(_v1:GetChildren()) do
        local f = v:FindFirstChild("\70\117\110\99\116\105\111\110\115")
        if f and f:FindFirstChild("\79\112\101\110\69\103\103") then
            return f.OpenEgg
        end
    end
    return nil
end

local _target = _v2:FindFirstChild(_0x5a2f[6]) and (_v2[_0x5a2f[6]]:FindFirstChild(_settings.e) or _v2[_0x5a2f[6]]:FindFirstChild(_settings.e .. " \69\103\103"))

if _target then
    _clean()
    _fx()
    _hide(_target)
    
    if _v5.Character then
        _v5.Character:PivotTo(_target:GetPivot() * CFrame.new(0, 0, 2))
    end
    
    _G.AutoHatch = true
    task.spawn(function()
        while _G.AutoHatch do
            local r = _getRemote()
            if r then
                local s = r:InvokeServer(_settings.e, _settings.a)
                if not s then r:InvokeServer(_settings.e .. " \69\103\103", _settings.a) end
            end
            task.wait(_settings.s)
        end
    end)
end
